# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11277541f249f88ef6c729c49e36ceaea76f5cfad8c99441273a5297fff0e2f1e1128d4627538ef17528d975450cb9eb02fd1635acf3b5e1e157e17bfcd8175f

test:
  secret_key_base: 37982fba4dde0be0ab44675c8e2a30b5be09669cc03715864e9f26fecb3080aa9ebe16c4528ecfe797aa55a8e90eea432b21fc9696dfd5707b0a818bb8dec50c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
